--- #YAML:1.0
name:               IO-AIO-Util
version:            0.07
abstract:           useful functions missing from IO::AIO
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec::Functions:  0
    IO::AIO:              2
    POSIX:                0
    Test::More:           0
resources:
    repository:  http://github.com/gray/io-aio-util
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
